services:
  # DATABASE
  db:
    image: postgres:17
    container_name: f2fantasy_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: f2fantasy_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  # BACKEND
  backend:
    build: ./backend
    container_name: f2_backend
    ports:
      - "5000:5000"
    environment:
      DB_USER: postgres
      DB_PASSWORD: password
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: f2_fantasy
    depends_on:
      - db

  # FRONTEND
  frontend:
    build: ./frontend
    container_name: f2_frontend
    restart: always
    ports:
      - "3000:80" # puerto 80 del contenedor al 3000

volumes:
  pgdata: